{% set version = "1.7.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-heplots
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/heplots_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/heplots/heplots_{{ version }}.tar.gz
  sha256: 8bd13e2c15f3335eba9dcf535646612125e9ae2de0ce1f304788a786700b2555

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-car >=3.0
    - r-rgl
  run:
    - r-base
    - r-mass
    - r-car >=3.0
    - r-rgl

test:
  commands:
    - $R -e "library('heplots')"           # [not win]
    - "\"%R%\" -e \"library('heplots')\""  # [win]

about:
  home: http://datavis.ca/R/index.php#heplots
  license: GPL-2.0-or-later
  summary: Provides HE plot and other functions for visualizing hypothesis tests in multivariate linear models. HE plots represent sums-of-squares-and- products matrices for linear hypotheses and for error using ellipses (in two dimensions) and ellipsoids (in three dimensions). The related 'candisc' package provides visualizations
    in a reduced-rank canonical discriminant space when there are more than a few response variables.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
