{% set version = "1.3-7" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-heplots
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/heplots_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/heplots/heplots_{{ version }}.tar.gz
  sha256: be3add93125f4e66d9f42b73ecfd14f855428f4f273f381abc381c3cee7e28dd

build:
  number: 0
  noarch: generic
  merge_build_host: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-car
  run:
    - r-base
    - r-mass
    - r-car

test:
  commands:
    - $R -e "library('heplots')"           # [not win]
    - "\"%R%\" -e \"library('heplots')\""  # [win]

about:
  home: http://datavis.ca/R/index.php#heplots
  license: GPL (>= 2)
  summary: Provides HE plot and other functions for visualizing hypothesis tests in multivariate linear models. HE plots represent sums-of-squares-and- products matrices for linear hypotheses and for error using ellipses (in two dimensions) and ellipsoids (in three dimensions). The related 'candisc' package provides visualizations
    in a reduced-rank canonical discriminant space when there are more than a few response variables.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
