appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: 2DONYmWjhPtSsjwGxUFao5kGdSthmA8pYApxjEr/kE+f3LmYLXyGS/2TOHNs0GTWycGts2jSj84bUCRaIrLvsEr3Vyu44hqW+ZwtjY9A4DTcTfLGBFM3qFpNuqojNvk5SJOK8YJcNtm5kzsW98zUvzZWiQXzH6ng78AYcH58wU0eFu/qm8/PlFl2TOoxxofIRhcRwN60EN33xERIBp51vIpLC1c9ypewQBV59sypHKXKkhX0xm/O/qXNoXiQ7lQTW+tosYEz/0ttdHTTCu9ffmyitaHG7ufuPBPMKQT670XeX4meCgZQCoYUeUAk5PwomW+49sonHX9oEiy+z62O/QTgJWUdBOmWZiOHhljLBPMKjDfSXYXdu8tYXeP6wII3vv+EQv73HaOJNezNuFPAlHAnRcdIAAjqgSSVKvcolSC8Huq68lcESvER5Kj601MnFmoDNLXrSZO1CwCEOkpv3+X7QQDKcmrnqKrq6BilRyT5+GfWc2vTdwt0XzXKcIpg6lUJUcK/+7g750c64MnF4RHS6CbHOulexjTh7EnpIoBo198Iz8gjbhEPR5DjufAWLKkI2rFRJ0sJQrS4942lruixZyHNe3+VNmF5cHzBykYgJALhsFE0DiXkqRBF3o0fNCBT4D4c7RgiQDfbpy22sgxNMbMPptV6XbJ56GkSAqg=
